/**
 * Generic "fence" primitives for marking CLI-managed spans inside files the
 * CLI does not otherwise own outright — files that mix toolcrib-authored
 * content with the user's own (AGENTS.md/CLAUDE.md, .gitignore, and
 * eventually app source files). Different file types comment differently,
 * so the fence syntax is parameterized by "style" rather than hardcoded to
 * one comment form. See lib/managedDocs.js for the Markdown-specific
 * application of this to ai-docs content merged into AGENTS.md/CLAUDE.md.
 *
 * Known limitation: content containing a literal occurrence of the style's
 * own end-comment text would prematurely close the fence. Not defended
 * against — it doesn't occur in any content this CLI currently generates,
 * and guarding against it would add real complexity for a case that isn't
 * happening in practice.
 */

// \r?\n, never a bare \n, in every pattern below: `git apply` writes files
// with CRLF whenever core.autocrlf=true (the common Windows Git default —
// confirmed via a real end-to-end run where this was originally \n-only and
// silently matched zero blocks against a real CRLF-checked-out AGENTS.md,
// with no error, just silent non-detection). extractFence()/upsertFence()
// still return/compare content run through normalize() by their callers
// (doctor.js, merge.js) so a pure line-ending difference is never itself
// reported as drift — this fix is about matching the fence at all.
// Unlike vendored component source (meant to be forked/customized freely),
// content inside a managed fence is meant to be regenerated, not hand-edited
// — so every fence carries a visible warning to that effect. The warning
// text itself is stripped back out by extractFence() before content is
// returned/compared (see below), so rewording it later doesn't invalidate
// old fences, and it never shows up as spurious drift.
function bannerFor(style) {
  const text =
    "Auto-generated by toolcrib — do not edit by hand, it will be overwritten by 'toolcrib merge'. " +
    'Add your own notes outside this block instead.';
  return style === 'markdown' ? `<!-- ${text} -->` : style === 'hash' ? `# ${text}` : `// ${text}`;
}

function escapeRegExp(text) {
  return text.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

export const FENCE_STYLES = {
  // Markdown / HTML-comment files: AGENTS.md, CLAUDE.md.
  markdown: {
    start: (id, version) => `<!-- toolcrib:managed:${id}:start version=${version} -->`,
    banner: () => bannerFor('markdown'),
    end: (id) => `<!-- toolcrib:managed:${id}:end -->`,
    // \r?\n, never a bare \n, here and in every pattern below: `git apply`
    // writes files with CRLF whenever core.autocrlf=true (the common
    // Windows Git default — confirmed via a real end-to-end run where this
    // was originally \n-only and silently matched zero blocks against a
    // real CRLF-checked-out AGENTS.md, with no error, just silent
    // non-detection). extractFence()/upsertFence() still return/compare
    // content run through normalize() by their callers (doctor.js,
    // merge.js) so a pure line-ending difference is never itself reported
    // as drift — this is about matching the fence at all.
    //
    // `id` is escaped before interpolation into the RegExp source — every
    // `id` this CLI actually passes today is a fixed internal constant
    // ('gitignore', 'core', 'new-app', 'refactor-app'), never attacker- or
    // even user-controlled, so this has never been reachable in practice.
    // Escaping anyway costs nothing and means that stays true by
    // construction rather than by every future caller happening to keep
    // passing safe ids — the same reasoning as escaping the version string,
    // just not yet applied here consistently.
    pattern: (id) => {
      const safeId = escapeRegExp(id);
      return new RegExp(
        `<!-- toolcrib:managed:${safeId}:start version=(\\S+) -->\\r?\\n([\\s\\S]*?)<!-- toolcrib:managed:${safeId}:end -->\\r?\\n?`
      );
    },
  },
  // #-comment files: .gitignore, .env, YAML, shell scripts.
  hash: {
    start: (id, version) => `# toolcrib:managed:${id}:start version=${version}`,
    banner: () => bannerFor('hash'),
    end: (id) => `# toolcrib:managed:${id}:end`,
    pattern: (id) => {
      const safeId = escapeRegExp(id);
      return new RegExp(`# toolcrib:managed:${safeId}:start version=(\\S+)\\r?\\n([\\s\\S]*?)# toolcrib:managed:${safeId}:end\\r?\\n?`);
    },
  },
  // JS/TS/JSX/TSX source files. Not used by any current CLI feature — no
  // command patches user source code yet — but defined here so a future
  // one (e.g. auto-inserting the ThemeProvider/ToastProvider root wiring
  // from NEW_APP.md into main.tsx) has a ready-made, consistent style
  // rather than inventing another ad-hoc convention.
  js: {
    start: (id, version) => `// toolcrib:managed:${id}:start version=${version}`,
    banner: () => bannerFor('js'),
    end: (id) => `// toolcrib:managed:${id}:end`,
    pattern: (id) => {
      const safeId = escapeRegExp(id);
      return new RegExp(`// toolcrib:managed:${safeId}:start version=(\\S+)\\r?\\n([\\s\\S]*?)// toolcrib:managed:${safeId}:end\\r?\\n?`);
    },
  },
};

// JSON has no comment syntax, so it cannot carry a textual fence at all —
// noted here rather than silently unsupported. The one JSON asset this CLI
// patches (package.json) is instead tracked structurally, by known
// dependency/imports key names (see lib/deps.js), not by an inline marker.
export const NO_FENCE_ASSET_TYPES = ['json'];

/** Build a complete fenced block (start marker, banner, content, end marker) in the given style. */
export function buildFence(style, id, version, content) {
  const banner = style.banner ? `${style.banner()}\n` : '';
  return `${style.start(id, version)}\n${banner}${content.trimEnd()}\n${style.end(id)}\n`;
}

/**
 * Find an existing fenced block for `id` in `fileContent`. Returns null if
 * absent. The "do not edit" banner (if this style has one) is stripped from
 * the returned content — it's a fence-structure concern, not part of the
 * actual doc content being tracked, and leaving it in would make every
 * block compare as different from the pristine source that never had it.
 */
export function extractFence(style, fileContent, id) {
  const match = style.pattern(id).exec(fileContent);
  if (!match) return null;
  let content = match[2];
  if (style.banner) {
    const bannerLine = new RegExp(`^${escapeRegExp(style.banner())}\\r?\\n`);
    content = content.replace(bannerLine, '');
  }
  return { version: match[1], content: content.trimEnd(), raw: match[0] };
}

/**
 * Insert or replace the fenced block for `id` in `fileContent`.
 * If a block for this id already exists, only that span is replaced —
 * everything else in the file is left untouched. Otherwise the block is
 * appended.
 */
export function upsertFence(style, fileContent, id, version, content) {
  const newBlock = buildFence(style, id, version, content);
  const regex = style.pattern(id);
  if (regex.test(fileContent)) {
    return fileContent.replace(regex, newBlock);
  }
  if (fileContent.length === 0) return newBlock;
  const separator = fileContent.endsWith('\n\n') ? '' : fileContent.endsWith('\n') ? '\n' : '\n\n';
  return fileContent + separator + newBlock;
}
