import React, { createContext, useContext, useState, ReactNode, useCallback } from 'react';
import { useAIEvent } from '../../eventBus/useAIEvent';
import { aiBus } from '../../eventBus/eventBus';
import { SubthemeName } from '../../theme/subtheme';

/** Toast urgency level. Higher priority toasts are displayed first. */
/** @barrelExport */
export type ToastPriority = 'low' | 'medium' | 'high' | 'urgent';
/** Visual style variant for toasts — the same vocabulary as `SubthemeName`. */
export type ToastType = SubthemeName;
/** Screen corner where the toast stack is anchored. */
export type ToastAnchor =
  | 'top-right'
  | 'top-left'
  | 'bottom-right'
  | 'bottom-left'
  | 'top-center'
  | 'bottom-center';

/** An action button rendered inside a toast notification. */
export interface ToastAction {
  /** Button label text. */
  label: string;
  /** Callback when the action button is clicked. */
  onClick: () => void;
}

/**
 * Data shape for a single toast notification.
 *
 * Create toasts via `aiBus.showToast()` or `addToast()` from `useToast()`.
 */
export interface ToastItem {
  /** Unique identifier. Auto-generated by `addToast` / `aiBus.showToast`. */
  id: string;
  /** Visual type controlling colour and icon. */
  type: ToastType;
  /** Main message text displayed in the toast body. */
  message: string;
  /** Optional bold title above the message. */
  title?: string;
  /** Auto-dismiss duration in milliseconds. 0 or omit for sticky. @default 5000 */
  duration?: number;
  /** If true, toast requires explicit user dismissal and never auto-expires. */
  sticky?: boolean;
  /** Display priority. Higher-priority toasts sort to top. @default 'medium' */
  priority?: ToastPriority;
  /** Screen corner override for this specific toast. Defaults to provider anchor. */
  anchor?: ToastAnchor;
  /** Action buttons rendered in the toast. */
  actions?: ToastAction[];
}

/**
 * Context value exposed by `<ToastProvider>`.
 *
 * Prefer `aiBus.showToast()` for simple use cases.
 * Use `useToast()` for advanced control (custom anchors, actions, sticky toasts).
 */
export interface ToastContextType {
  /** Currently visible toast items. */
  toasts: ToastItem[];
  /** Add a toast and return its id. */
  addToast: (toast: Omit<ToastItem, 'id'> & { id?: string }) => string;
  /** Dismiss a specific toast by id. */
  dismissToast: (id: string, reason?: 'user' | 'expired' | 'action') => void;
  /** Dismiss all visible toasts. */
  clearAll: () => void;
  /** Change the global anchor position for the toast stack. */
  setAnchor: (anchor: ToastAnchor) => void;
  /** Current global anchor position. */
  anchor: ToastAnchor;
}

const ToastContext = createContext<ToastContextType | undefined>(undefined);

const PRIORITY_WEIGHT: Record<ToastPriority, number> = {
  urgent: 4,
  high: 3,
  medium: 2,
  low: 1,
};

export interface ToastProviderProps {
  children: ReactNode;
  defaultAnchor?: ToastAnchor;
}

export const ToastProvider: React.FC<ToastProviderProps> = ({
  children,
  defaultAnchor = 'top-right',
}) => {
  const [toasts, setToasts] = useState<ToastItem[]>([]);
  const [anchor, setAnchor] = useState<ToastAnchor>(defaultAnchor);

  const addToast = useCallback((toastData: Omit<ToastItem, 'id'> & { id?: string }): string => {
    const id = toastData.id || `toast-${Date.now()}-${Math.random().toString(36).substring(2, 7)}`;
    const isSticky = Boolean(toastData.sticky || toastData.duration === 0 || toastData.priority === 'urgent');
    const duration = isSticky ? 0 : (toastData.duration !== undefined ? toastData.duration : 5000);

    const newToast: ToastItem = {
      id,
      priority: 'medium',
      anchor,
      ...toastData,
      sticky: isSticky,
      duration,
    };

    setToasts(prev => {
      const updated = [...prev.filter(t => t.id !== id), newToast];
      // Sort by priority (higher priority first)
      return updated.sort((a, b) => PRIORITY_WEIGHT[b.priority || 'medium'] - PRIORITY_WEIGHT[a.priority || 'medium']);
    });

    aiBus.emit('toast:added', {
      id,
      type: newToast.type,
      message: newToast.message,
      priority: newToast.priority,
    });

    return id;
  }, [anchor]);

  const dismissToast = useCallback((id: string, reason: 'user' | 'expired' | 'action' = 'user') => {
    let targetToast: ToastItem | undefined;
    setToasts(prev => {
      targetToast = prev.find(t => t.id === id);
      return prev.filter(t => t.id !== id);
    });

    aiBus.emit('toast:dismissed', {
      id,
      message: targetToast?.message,
      type: targetToast?.type,
      reason,
    });
  }, []);

  const clearAll = useCallback(() => {
    setToasts([]);
  }, []);

  // Listen to Event Bus for toast dispatching
  useAIEvent('toast:shown', event => {
    addToast({
      id: event.id,
      type: event.type,
      message: event.message,
      priority: event.priority || 'medium',
    });
  });

  return (
    <ToastContext.Provider
      value={{
        toasts,
        addToast,
        dismissToast,
        clearAll,
        setAnchor,
        anchor,
      }}
    >
      {children}
    </ToastContext.Provider>
  );
};

export const useToast = (): ToastContextType => {
  const context = useContext(ToastContext);
  if (!context) {
    throw new Error('useToast must be used within a ToastProvider');
  }
  return context;
};
