'use client';

import React, { createContext, useContext, useState, type ReactNode, useCallback, useMemo, useRef, useLayoutEffect } from 'react';
import { useAIEvent } from '../../eventBus/useAIEvent';
import { aiBus } from '../../eventBus/eventBus';
import { type SubthemeName } from '../../theme/subtheme';

/**
 * Toast urgency level -- controls duration/stickiness (`'urgent'` is
 * always sticky), not stacking position. Toasts always stack in FIFO
 * (insertion) order regardless of priority.
 */
/** @barrelExport */
export type ToastPriority = 'low' | 'medium' | 'high' | 'urgent';
/** Visual style variant for toasts — the same vocabulary as `SubthemeName`. */
export type ToastType = SubthemeName;
/** Screen corner where the toast stack is anchored. */
export type ToastAnchor =
  | 'top-right'
  | 'top-left'
  | 'bottom-right'
  | 'bottom-left'
  | 'top-center'
  | 'bottom-center';

/** An action button rendered inside a toast notification. */
export interface ToastAction {
  /** Button label text. */
  label: string;
  /** Callback when the action button is clicked. */
  onClick: () => void;
}

/**
 * Data shape for a single toast notification.
 *
 * Create toasts via `aiBus.showToast()` or `addToast()` from `useToast()`.
 */
export interface ToastItem {
  /** Unique identifier. Auto-generated by `addToast` / `aiBus.showToast`. */
  id: string;
  /** Visual type controlling colour and icon. */
  type: ToastType;
  /** Main message text displayed in the toast body. */
  message: string;
  /** Optional bold title above the message. */
  title?: string;
  /** Auto-dismiss duration in milliseconds. 0 or omit for sticky. @default 5000 */
  duration?: number;
  /** If true, toast requires explicit user dismissal and never auto-expires. */
  sticky?: boolean;
  /** Display priority -- affects duration/stickiness only, not stacking order (always FIFO). @default 'medium' */
  priority?: ToastPriority;
  /** Screen corner override for this specific toast. Defaults to provider anchor. */
  anchor?: ToastAnchor;
  /** Action buttons rendered in the toast. */
  actions?: ToastAction[];
}

/**
 * Context value exposed by `<ToastProvider>`.
 *
 * Prefer `aiBus.showToast()` for simple use cases.
 * Use `useToast()` for advanced control (custom anchors, actions, sticky toasts).
 */
export interface ToastContextType {
  /** Currently visible toast items. */
  toasts: ToastItem[];
  /** Add a toast and return its id. */
  addToast: (toast: Omit<ToastItem, 'id'> & { id?: string }) => string;
  /** Dismiss a specific toast by id. */
  dismissToast: (id: string, reason?: 'user' | 'expired' | 'action') => void;
  /** Dismiss all visible toasts. */
  clearAll: () => void;
  /** Change the global anchor position for the toast stack. */
  setAnchor: (anchor: ToastAnchor) => void;
  /** Current global anchor position. */
  anchor: ToastAnchor;
}

const ToastContext = createContext<ToastContextType | undefined>(undefined);

/**
 * The stable half of `ToastContextType`: just the actions, no toast list.
 * Returned by `useToastActions()`.
 */
export type ToastActions = Pick<ToastContextType, 'addToast' | 'dismissToast' | 'clearAll' | 'setAnchor'>;

// Issue #632: a separate context for the actions alone, memoized so its
// value only changes when an action itself does (addToast when the anchor
// changes; the rest never). ToastContext's value carries the live toasts
// array, so every useToast() consumer re-rendered whenever ANY toast was
// added or expired -- including components that only ever called addToast.
const ToastActionsContext = createContext<ToastActions | undefined>(undefined);

export interface ToastProviderProps {
  children: ReactNode;
  defaultAnchor?: ToastAnchor;
}

export const ToastProvider: React.FC<ToastProviderProps> = ({
  children,
  defaultAnchor = 'top-right',
}) => {
  const [toasts, setToasts] = useState<ToastItem[]>([]);
  const [anchor, setAnchor] = useState<ToastAnchor>(defaultAnchor);
  // dismissToast needs the dismissed toast's data (message/type) for the
  // `toast:dismissed` payload, but reads it via a `let` captured by the
  // setToasts updater and used immediately after the setToasts call —
  // relying on the updater having already run synchronously, which React 18
  // batching does not guarantee (two toasts auto-expiring in the same batch
  // is enough to break it, since only the first gets the eager-update
  // shortcut). Mirroring toasts into a ref keeps dismissToast referentially
  // stable (still `[]` deps, matching every other callback here) while
  // giving it a synchronously-current snapshot to read from instead.
  const toastsRef = useRef<ToastItem[]>(toasts);
  // useLayoutEffect, not a bare assignment during render -- writing to a
  // ref during render is unsafe under React's stricter rules (a discarded/
  // aborted render attempt could write a value that never actually
  // commits). useLayoutEffect runs synchronously right after commit,
  // before the browser paints or any event handler can run, so
  // dismissToast (called from an event handler or a later timer) still
  // sees a synchronously-current snapshot, same as this comment's
  // original "kept in sync" guarantee.
  useLayoutEffect(() => {
    toastsRef.current = toasts;
  }, [toasts]);

  const addToast = useCallback((toastData: Omit<ToastItem, 'id'> & { id?: string }): string => {
    const id = toastData.id || `toast-${Date.now()}-${Math.random().toString(36).substring(2, 7)}`;
    const isSticky = Boolean(toastData.sticky || toastData.duration === 0 || toastData.priority === 'urgent');
    const duration = isSticky ? 0 : (toastData.duration !== undefined ? toastData.duration : 5000);

    const newToast: ToastItem = {
      id,
      priority: 'medium',
      anchor,
      ...toastData,
      sticky: isSticky,
      duration,
    };

    // FIFO insertion order (issue #379) -- toasts used to be re-sorted by
    // priority on every insert, so a low-priority toast fired first could
    // end up visually below a high-priority one fired later. Priority
    // still independently controls duration/stickiness (isSticky above),
    // just not stacking position: a toast always stacks in the order it
    // was actually triggered.
    setToasts(prev => [...prev.filter(t => t.id !== id), newToast]);

    aiBus.emit('toast:added', {
      id,
      type: newToast.type,
      message: newToast.message,
      priority: newToast.priority,
    });

    return id;
  }, [anchor]);

  const dismissToast = useCallback((id: string, reason: 'user' | 'expired' | 'action' = 'user') => {
    const targetToast = toastsRef.current.find(t => t.id === id);
    setToasts(prev => prev.filter(t => t.id !== id));

    aiBus.emit('toast:dismissed', {
      id,
      message: targetToast?.message,
      type: targetToast?.type,
      reason,
    });
  }, []);

  const clearAll = useCallback(() => {
    setToasts([]);
  }, []);

  // Listen to Event Bus for toast dispatching
  useAIEvent('toast:shown', event => {
    addToast({
      id: event.id,
      type: event.type,
      message: event.message,
      priority: event.priority || 'medium',
    });
  });

  const actions = useMemo<ToastActions>(
    () => ({ addToast, dismissToast, clearAll, setAnchor }),
    // setAnchor is a useState setter (stable by React's guarantee, and exempt
    // from exhaustive-deps) -- listed anyway so the memo stays correct if it's
    // ever replaced with a custom function.
    [addToast, dismissToast, clearAll, setAnchor]
  );

  return (
    <ToastActionsContext.Provider value={actions}>
      <ToastContext.Provider
        value={{
          toasts,
          addToast,
          dismissToast,
          clearAll,
          setAnchor,
          anchor,
        }}
      >
        {children}
      </ToastContext.Provider>
    </ToastActionsContext.Provider>
  );
};

export const useToast = (): ToastContextType => {
  const context = useContext(ToastContext);
  if (!context) {
    throw new Error('useToast must be used within a ToastProvider');
  }
  return context;
};

/**
 * Just the toast actions (`addToast`, `dismissToast`, `clearAll`,
 * `setAnchor`), without the live toast list. Prefer this over `useToast()`
 * in any component that only fires toasts: a `useToast()` consumer
 * re-renders every time any toast is added, updated or expires, while
 * this value stays referentially stable (issue #632).
 */
export const useToastActions = (): ToastActions => {
  const context = useContext(ToastActionsContext);
  if (!context) {
    throw new Error('useToastActions must be used within a ToastProvider');
  }
  return context;
};
