import path from 'node:path';
import * as p from '@clack/prompts';
import { fetchRelease } from '../lib/release.js';
import { normalize } from '../lib/patches.js';
import { readJsonIfExists, readLock, readTextIfExists } from '../lib/project.js';
import { listVersions } from '../lib/github.js';
import { MANAGED_DOCS, KNOWN_TARGET_FILES, listManagedBlocks } from '../lib/managedDocs.js';
import { detectBundler } from '../lib/bundler.js';

const TOOLKIT_DIR = './toolcrib';

// moduleResolution modes under which TypeScript actually reads package.json
// "imports" subpaths (what makes `import { Card } from '#toolcrib'`
// type-check, not just run). Anything else — including TS's own default —
// resolves the import at runtime via bundler/Node but reports a false
// "Cannot find module" in the editor and tsc.
const IMPORTS_COMPATIBLE_MODULE_RESOLUTIONS = new Set(['bundler', 'node16', 'nodenext']);

/**
 * Read-only check: will `import ... from '#toolcrib'` type-check under this
 * project's tsconfig? Returns null when there's nothing to warn about (no
 * tsconfig.json — e.g. a plain JS project — or an already-compatible
 * moduleResolution). Otherwise returns the offending value for the warning
 * message ('' meaning unset/default).
 */
export function checkImportsCompatibility(projectRoot) {
  const tsconfig = readJsonIfExists(path.join(projectRoot, 'tsconfig.json'));
  if (!tsconfig) return null;

  const moduleResolution = (tsconfig.compilerOptions?.moduleResolution || '').toLowerCase();
  if (IMPORTS_COMPATIBLE_MODULE_RESOLUTIONS.has(moduleResolution)) return null;

  return moduleResolution;
}

/**
 * Read-only drift check for managed <!-- toolcrib:managed:... --> blocks
 * inside AGENTS.md/CLAUDE.md — the same question the vendored-file drift
 * check above answers, but for content merged into files the CLI doesn't
 * otherwise own. `installedRelease` (already fetched for the vendored-file
 * check) is reused when a block's own recorded version matches the
 * installed one — the common case — rather than re-fetching.
 */
export async function checkManagedBlocks(projectRoot, installedRelease) {
  const messages = [];

  for (const targetFile of KNOWN_TARGET_FILES) {
    const content = readTextIfExists(path.join(projectRoot, targetFile));
    if (!content) continue;

    for (const block of listManagedBlocks(content)) {
      const docFile = MANAGED_DOCS[block.docId];

      let originalDocContent;
      try {
        if (block.version === installedRelease.version) {
          originalDocContent = installedRelease.readFile(`ai-docs/${docFile}`);
        } else {
          const atVersionRelease = await fetchRelease(block.version);
          originalDocContent = atVersionRelease.readFile(`ai-docs/${docFile}`);
          await atVersionRelease.cleanup();
        }
      } catch {
        messages.push({
          level: 'warn',
          text: `${targetFile}: managed block "${block.docId}" claims version ${block.version}, which no longer resolves to a release — can't verify drift.`,
        });
        continue;
      }

      // block.content was already trimEnd()'d at extraction (see
      // extractFence) — originalDocContent is a raw file read and still has
      // its trailing newline, so it must be trimmed the same way before
      // comparing, or every block would falsely register as drifted purely
      // from that trailing newline (confirmed via a real end-to-end run:
      // this fired for every managed block, not just hand-edited ones).
      if (normalize(block.content) !== normalize(originalDocContent).trimEnd()) {
        messages.push({
          level: 'warn',
          text: `${targetFile}: managed block "${block.docId}" (v${block.version}) was edited by hand — it's meant to be regenerated by 'toolcrib merge', not edited directly. Move your own notes outside the fence, then run 'toolcrib merge' to restore it.`,
        });
      }
      if (block.version !== installedRelease.version) {
        messages.push({
          level: 'info',
          text: `${targetFile}: managed block "${block.docId}" is at v${block.version}, installed toolkit is v${installedRelease.version} — run 'toolcrib merge' to update it too.`,
        });
      }
    }
  }

  return messages;
}

/**
 * Reports drift without staging any patches — a read-only diagnostic.
 * "No drift" here answers a different question than "are you on the
 * latest version," which is checked separately below; the two are
 * deliberately not conflated (see design notes).
 */
export async function doctorCommand() {
  const projectRoot = process.cwd();
  p.intro('toolcrib doctor');

  const lock = readLock(projectRoot);
  if (!lock) {
    p.log.error('No toolcrib install found. Run `toolcrib init` first.');
    process.exitCode = 1;
    return;
  }

  const spinner = p.spinner();
  spinner.start(`Checking against installed version v${lock.version}`);
  let release;
  try {
    release = await fetchRelease(lock.version);
  } catch (err) {
    spinner.stop('Failed to fetch release');
    throw err;
  }

  const drifted = [];
  for (const relPath of release.allFiles()) {
    const targetPath = path.join(projectRoot, TOOLKIT_DIR, relPath);
    const local = readTextIfExists(targetPath);
    const shipped = release.readFile(relPath);
    if (normalize(local) !== normalize(shipped)) {
      drifted.push(relPath);
    }
  }
  const managedBlockMessages = await checkManagedBlocks(projectRoot, release);
  await release.cleanup();
  spinner.stop('Drift check complete');

  if (drifted.length === 0) {
    p.log.success(`No local drift detected from v${lock.version}.`);
  } else {
    p.log.warn(
      `${drifted.length} file(s) differ from the shipped v${lock.version}:\n` +
        drifted.map((f) => `  ${f}`).join('\n')
    );
  }

  if (managedBlockMessages.length === 0) {
    p.log.success('No managed AGENTS.md/CLAUDE.md blocks found, or none have drifted.');
  } else {
    for (const message of managedBlockMessages) {
      p.log[message.level](message.text);
    }
  }

  const versions = await listVersions();
  const newest = versions.find((v) => !v.prerelease);
  if (newest && newest.version !== lock.version) {
    p.log.info(`A newer version is available: v${newest.version} (installed: v${lock.version}). Run 'toolcrib merge'.`);
  } else {
    p.log.info('You are on the latest release.');
  }

  const badModuleResolution = checkImportsCompatibility(projectRoot);
  if (badModuleResolution !== null) {
    p.log.warn(
      `tsconfig.json's "moduleResolution" is ${badModuleResolution ? `"${badModuleResolution}"` : 'unset (defaulting to a legacy mode)'}, ` +
        `which doesn't type-check package.json "imports" subpaths. The toolkit's ` +
        `\`import { ... } from '#toolcrib'\` will still run correctly (bundlers and Node resolve it fine), ` +
        `but tsc/your editor may report "Cannot find module '#toolcrib'". ` +
        `Set "moduleResolution": "bundler" (or "node16"/"nodenext") in compilerOptions to fix the false error.`
    );
  }

  const pkg = readJsonIfExists(path.join(projectRoot, 'package.json'));
  const bundler = detectBundler(projectRoot, pkg);
  if (bundler?.note) {
    p.log.info(`Detected ${bundler.label} — ${bundler.note}`);
  }

  p.outro('Done.');
}
