import fs from 'node:fs';
import path from 'node:path';
import { describe, it, expect } from 'vitest';
import { isGeneratedPath, filterGeneratedFromDiff } from './generatedPaths.js';

// Reads build-graph.json directly -- see buildGraph.test.js for why
// buildGraph.js itself can't be imported under Vitest.
function readGraph() {
  const graphPath = path.resolve(process.cwd(), 'scripts', 'lib', 'build-graph.json');
  return JSON.parse(fs.readFileSync(graphPath, 'utf-8')).nodes;
}

const SYNTHETIC = [{ id: 'x', inputs: [], outputs: ['out/file.json', 'gen/**'] }];

function section(file, body = '+changed') {
  return `diff --git a/${file} b/${file}\nindex 111..222 100644\n--- a/${file}\n+++ b/${file}\n@@ -1 +1 @@\n${body}`;
}

describe('isGeneratedPath', () => {
  it('matches exact outputs, subtree outputs and lockfiles anywhere', () => {
    expect(isGeneratedPath(SYNTHETIC, 'out/file.json')).toBe(true);
    expect(isGeneratedPath(SYNTHETIC, 'gen/deep/a.md')).toBe(true);
    expect(isGeneratedPath(SYNTHETIC, 'package-lock.json')).toBe(true);
    expect(isGeneratedPath(SYNTHETIC, 'cli/package-lock.json')).toBe(true);
    expect(isGeneratedPath(SYNTHETIC, 'src/out/file.json')).toBe(false);
    expect(isGeneratedPath(SYNTHETIC, 'generator.js')).toBe(false);
  });

  it('covers every generated artifact in the real graph, and not its sources', () => {
    const graph = readGraph();
    for (const f of [
      'ai-docs/component-manifest.json',
      'ai-docs/manifest/overlays.json',
      'ai-docs/CORE.md',
      'ai-docs/examples/dashboard.md',
      'llms.txt',
      'llms-full.txt',
      'src/index.ts',
      'demo/demoSources.generated.json',
      'security-advisories.json',
      'scripts/package-lock.json',
    ]) {
      expect(isGeneratedPath(graph, f), f).toBe(true);
    }
    for (const f of ['ai-docs/templates/CORE.md.hbs', 'ai-docs/NEW_APP.md', 'src/components/Overlay/Modal.tsx', 'package.json', 'AGENTS.md']) {
      expect(isGeneratedPath(graph, f), f).toBe(false);
    }
  });
});

describe('filterGeneratedFromDiff', () => {
  it('drops whole sections for generated files and keeps the rest intact', () => {
    const input = [section('src/a.ts', '+keep a'), section('package-lock.json', '+drop'), section('gen/x.md', '+drop too'), section('src/b.ts', '+keep b')].join('\n');
    const { diff, omitted } = filterGeneratedFromDiff(SYNTHETIC, input);
    expect(omitted).toEqual(['package-lock.json', 'gen/x.md']);
    expect(diff).toBe([section('src/a.ts', '+keep a'), section('src/b.ts', '+keep b')].join('\n'));
  });

  it('keeps a diff with nothing generated byte-for-byte', () => {
    const input = [section('src/a.ts'), section('src/b.ts')].join('\n') + '\n';
    expect(filterGeneratedFromDiff(SYNTHETIC, input)).toEqual({ diff: input, omitted: [] });
  });

  it('recognizes headers in CRLF input', () => {
    const input = [section('package-lock.json'), section('src/a.ts')].join('\n').replace(/\n/g, '\r\n');
    expect(filterGeneratedFromDiff(SYNTHETIC, input).omitted).toEqual(['package-lock.json']);
  });

  it('keys on the b/ path, so a file renamed into a generated path is dropped', () => {
    const input = 'diff --git a/src/old.json b/out/file.json\nsimilarity index 100%\nrename from src/old.json\nrename to out/file.json';
    expect(filterGeneratedFromDiff(SYNTHETIC, input).omitted).toEqual(['out/file.json']);
  });

  it('does not treat a "diff --git" line inside a hunk as a header', () => {
    // Hunk lines always start with +, - or a space, so the header regex
    // (anchored at ^diff) can't match one.
    const input = section('src/a.ts', '+diff --git a/package-lock.json b/package-lock.json');
    expect(filterGeneratedFromDiff(SYNTHETIC, input).omitted).toEqual([]);
  });
});
